spring:
  datasource:
    url: jdbc:mysql://localhost:3306/footballequalizer?serverTimezone=Europe/Warsaw&useSSL=False&allowPublicKeyRetrieval=true
    username: footballEqualizer_user
    password: footballEqualizer_password
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: monolith-service

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs/${spring.application.name}

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/